import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'INFORMATION',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'doc', id: 'index', label: 'About us' },
        'information/team',
        'information/donations',
        'information/roadmap',
      ],
    },
    {
      type: 'category',
      label: 'FEATURE',
      collapsible: false,
      collapsed: false,
      items: [
        'feature/profile',
        'feature/leveling',
        'feature/wallet',
        'feature/premium',
        'feature/clicker',
        'feature/currency',
        {
          type: 'category',
          label: 'RPG',
          items: [{ type: 'autogenerated', dirName: 'feature/rpg' }],
        },
        'feature/marketplace',
        'feature/minigame',
      ],
    },
    {
      type: 'category',
      label: 'DISCORD BOT',
      collapsible: false,
      collapsed: false,
      items: [
        'discord-bot/commands',
        {
          type: 'category',
          label: 'Badge',
          items: [{ type: 'autogenerated', dirName: 'discord-bot/badge' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'BLOCKCHAIN',
      collapsible: false,
      collapsed: false,
      items: [
        'blockchain/token',
        {
          type: 'category',
          label: 'NFT',
          items: [{ type: 'autogenerated', dirName: 'blockchain/nft' }],
        },
        'blockchain/supported-chain-token',
      ],
    },
    {
      type: 'category',
      label: 'COMMUNITY GUIDELINES',
      collapsible: false,
      collapsed: false,
      items: [
        'community-guidelines/reward-eligibility',
      ],
    },
    {
      type: 'category',
      label: 'SUPPORT',
      collapsible: false,
      collapsed: false,
      items: [
        'support/faq',
        'support/contact-support',
      ],
    },
    {
      type: 'category',
      label: 'LEGAL',
      collapsible: false,
      collapsed: false,
      items: [
        'legal/terms-of-service',
        'legal/privacy-policy',
      ],
    },
    {
      type: 'link',
      label: 'X',
      href: 'https://x.com/miruka_bot',
    },
    {
      type: 'link',
      label: 'Support server',
      href: 'https://discord.gg/8yfv46W',
    },
  ],
};

export default sidebars;
